name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: |
          choco install conan --params "/PathType:'User'"
      - run: |
          conan --version
