name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: |
          choco install conan --params "/PathType:'Machine'"
      - run: |
          $env:PATH -split ';'
      - run: |
          Get-ChildItem -Recurse -Path "C:\Program Files\Conan"
      - run: |
          & "C:\Program Files\Conan\conan\conan.exe" --version
      - run: |
          conan --version
